site_name: 通读比特币白皮书
nav:
  - Home: index.md
  - 0. Abstract 摘要: wp00.md
  - 1. Introduction 简介: wp01.md
  - 2. Transactions 交易: wp02.md
  - 3. Timestamp Server 时间戳服务器: wp03.md
  - 4. Proof-of-Work 工作量证明: wp04.md
  - 5. Network 网络: wp05.md
  - 6. Incentive 激励: wp06.md
  - 7. Reclaiming Disk Space 回收磁盘空间: wp07.md
  - 8. Simplified Payment Verification 简化支付验证: wp08.md
  - 9. Combining and Splitting Value 合并和分割交易额: wp09.md
  - 10. Privacy 隐私: wp10.md
theme: readthedocs